/* Pricing Engine */
const plans=[
 {name:'الأساسية',annual:1140,monthly:120,users:1,warehouses:1,invoices:100,employees:1,manufacturing:false},
 {name:'المتقدمة',annual:1860,monthly:220,users:2,warehouses:3,invoices:500,employees:2,manufacturing:false},
 {name:'الشاملة',annual:2700,monthly:320,users:2,warehouses:5,invoices:Infinity,employees:3,manufacturing:true}
];
const rates={annual:{user:315,branch:1860,warehouse:540,employee:99},monthly:{user:35,branch:195,warehouse:58.5,employee:11.25}};
let billingPeriod='annual';
const byId=id=>document.getElementById(id);
const number=id=>Math.max(0,Number(byId(id).value)||0);
const currency=value=>Number(value||0).toLocaleString('ar-SA',{maximumFractionDigits:2});

function customerRequirements(){return{users:Math.max(1,number('users')),branches:Math.max(1,number('branches')),warehouses:Math.max(1,number('warehouses')),invoices:number('invoices'),employees:Math.max(1,number('employees')),manufacturing:byId('manufacturing').checked};}
function limitations(plan,index,requirements){const reasons=[];if(requirements.manufacturing&&!plan.manufacturing)reasons.push('التصنيع / BOM مطلوب وهو غير متاح');if(index===0&&requirements.branches>1)reasons.push(`عدد الفروع (${requirements.branches}) يتجاوز حد فرع واحد`);if(requirements.invoices>plan.invoices&&plan.invoices!==Infinity)reasons.push(`الفواتير (${requirements.invoices}) تتجاوز الحد (${plan.invoices})`);return reasons;}
function planQuote(plan,index,requirements){const rate=rates[billingPeriod],base=plan[billingPeriod],addons=Math.max(0,requirements.users-plan.users)*rate.user+Math.max(0,requirements.branches-1)*rate.branch+Math.max(0,requirements.warehouses-plan.warehouses)*rate.warehouse+Math.max(0,requirements.employees-plan.employees)*rate.employee;return{plan,index,base,addons,preTax:base+addons,limitations:limitations(plan,index,requirements)};}
function quotes(){const requirements=customerRequirements();return plans.map((plan,index)=>planQuote(plan,index,requirements));}

/* VAT Engine */
function vatEnabled(){return byId('vatIncluded').checked;}
function displayPrice(preTax){const vat=preTax*.15;return{base:preTax,vat,total:preTax+vat,shown:vatEnabled()?preTax+vat:preTax};}
function priceDetails(preTax){const price=displayPrice(preTax);return vatEnabled()?`<div class="price-details">السعر الأساسي: ${currency(price.base)} ر.س<br>VAT (15%): ${currency(price.vat)} ر.س<br><b>الإجمالي: ${currency(price.total)} ر.س</b></div>`:`<div class="price-details"><b>السعر الأساسي: ${currency(price.base)} ر.س</b><br>الأسعار لا تشمل الضريبة</div>`;}

/* Recommendation Engine */
function recommendation(){const allQuotes=quotes(),suitable=allQuotes.filter(quote=>!quote.limitations.length),selected=(suitable.length?suitable:allQuotes).sort((a,b)=>a.preTax-b.preTax)[0];const req=customerRequirements();const confidence=Math.max(45,97-(req.invoices>6000?7:0)-(req.branches>4?5:0)-(byId('need').value==='Low'?12:0));return{allQuotes,selected,suitable,confidence};}
function recommendationExplanation(selected,allQuotes){const rejected=allQuotes.filter(quote=>quote.index<selected.index&&quote.limitations.length);return `<b>لماذا تم اختيارها؟</b><br><span class="ok">✓ أقل باقة تحقق جميع المتطلبات دون تنازل</span>${rejected.map(quote=>quote.limitations.map(reason=>`<br><span class="bad">● ${quote.plan.name}: ${reason}</span>`).join('')).join('')||'<br><span class="ok">✓ لا توجد باقة أقل مناسبة</span>'}`;}

/* Proposal and WhatsApp Generators */
function whatsAppText(){const {selected,confidence}=recommendation(),requirements=customerRequirements(),price=displayPrice(selected.preTax);return `مرحباً ${byId('customerName').value||''}،\n\nنوصي بـ باقة ${selected.plan.name} لأنها أقل باقة تحقق متطلباتكم دون تنازلات.\n✓ ${requirements.users} مستخدم و${requirements.branches} فرع و${requirements.employees} موظف${requirements.manufacturing?' مع التصنيع':''}.\nثقة التوصية: ${confidence}%\n${vatEnabled()?`السعر الأساسي: ${currency(price.base)} ر.س\nVAT 15%: ${currency(price.vat)} ر.س\nالإجمالي: ${currency(price.total)} ر.س`:`السعر: ${currency(price.base)} ر.س (غير شامل VAT)`}\n\nيسعدنا استكمال الخطوات القادمة.`;}
function buildProposal(){const {selected}=recommendation(),req=customerRequirements(),price=displayPrice(selected.preTax);return `<header><h1 style="color:#0e3d36">دفتـرة ERP</h1><p>عرض تجاري · ${new Date().toLocaleDateString('ar-SA')}</p></header><h2>عرض إلى: ${byId('customerName').value}</h2><p>نوصي بباقة <b>${selected.plan.name}</b> لأنها أقل باقة مؤهلة تحقق المتطلبات.</p><table><tr><th>البند</th><th>التفاصيل</th></tr><tr><td>المستخدمون والفروع</td><td>${req.users} مستخدم · ${req.branches} فرع · ${req.warehouses} مستودع</td></tr><tr><td>الموظفون (الموارد البشرية)</td><td>${req.employees} موظف</td></tr><tr><td>الوحدات</td><td>المبيعات، المحاسبة، المخزون، CRM ${req.manufacturing?'، التصنيع':''}</td></tr><tr><td>السعر الأساسي</td><td>${currency(price.base)} ر.س</td></tr>${vatEnabled()?`<tr><td>ضريبة القيمة المضافة (15%)</td><td>${currency(price.vat)} ر.س</td></tr><tr><th>الإجمالي شامل الضريبة</th><th>${currency(price.total)} ر.س</th></tr>`:`<tr><th>الإجمالي قبل الضريبة</th><th>${currency(price.base)} ر.س</th></tr>`}</table><p>الشروط: الأسعار خاضعة للمراجعة والاعتماد النهائي من دفتـرة.</p><button class="btn primary" onclick="print()">تصدير PDF / طباعة</button> <button class="btn" onclick="proposalModal.classList.remove('show')">إغلاق</button>`;}

/* ROI Calculator */
function renderRoi(monthlyCost){const hours=number('wastedHours')*number('roiEmployees')*4,saved=hours*(number('averageSalary')/160);byId('timeSaved').textContent=currency(hours)+' ساعة';byId('moneySaved').textContent=currency(saved)+' ر.س';byId('roiValue').textContent=monthlyCost?Math.round(saved/monthlyCost*100)+'%':'—';}

/* Local Storage */
function saveDraft(){const data={};document.querySelectorAll('input,select,textarea').forEach(element=>data[element.id]=element.type==='checkbox'?element.checked:element.value);localStorage.setItem('daftraSalesAssistant',JSON.stringify({data,billingPeriod,dark:document.body.classList.contains('dark')}));}
function restoreDraft(){try{const saved=JSON.parse(localStorage.getItem('daftraSalesAssistant'));if(!saved)return;Object.entries(saved.data||{}).forEach(([id,value])=>{const element=byId(id);if(element)element.type==='checkbox'?element.checked=value:element.value=value;});billingPeriod=saved.billingPeriod||billingPeriod;document.body.classList.toggle('dark',saved.dark);}catch{}}
function quoteHistory(){return JSON.parse(localStorage.getItem('daftraQuoteHistory')||'[]');}

/* UI Rendering */
function renderPlans(){const {allQuotes,selected,suitable}=recommendation();byId('plans').innerHTML=allQuotes.map(quote=>{const selectedPlan=quote===selected,qualified=!quote.limitations.length;const tradeoff=qualified&&suitable.length>1?`<small>${selectedPlan?'ميزة: أقل تكلفة مؤهلة.':'ميزة: مرونة أعلى للنمو مقابل تكلفة أكبر.'}</small>`:'';return `<article class="plan ${selectedPlan?'best':''}" style="opacity:${qualified?1:.72}"><h3>${quote.plan.name} ${selectedPlan?'✓':''}</h3><div class="price">${currency(displayPrice(quote.preTax).shown)} <small>ر.س</small></div>${priceDetails(quote.preTax)}<div class="decision">${qualified?'<span class="ok">✓ مؤهلة: تغطي الاحتياج الحالي</span>':`<b class="bad">● غير مؤهلة</b><br>${quote.limitations.map(reason=>`<span class="bad">● ${reason}</span>`).join('<br>')}`}${selectedPlan?`<hr>${recommendationExplanation(selected,allQuotes)}`:''}</div>${tradeoff}</article>`;}).join('');}
function renderDashboard(){const {selected,confidence}=recommendation(),price=displayPrice(selected.preTax),monthly=price.shown/(billingPeriod==='annual'?12:1);byId('dashboardPlan').textContent='باقة '+selected.plan.name;byId('dashboardDeal').textContent=currency(price.shown)+' ر.س';byId('dashboardMrr').textContent=currency(monthly)+' ر.س';byId('dashboardScore').textContent=confidence+'%';byId('dashboardQualification').textContent=byId('need').value==='High'?'جاهزة للنقاش':'تحتاج استكشافاً إضافياً';}
function renderAssistant(){const {selected,confidence}=recommendation(),req=customerRequirements(),price=displayPrice(selected.preTax);byId('recommendationTitle').textContent='باقة '+selected.plan.name;byId('matchScore').textContent=confidence+'%';byId('scoreRing').style.setProperty('--score',confidence+'%');byId('consultantAdvice').innerHTML=`<span class="ok">ثقة التوصية: ${confidence}%</span><br>${recommendationExplanation(selected,quotes())}`;const items=[['العميل',byId('customerName').value||'غير محدد'],['النشاط',byId('activity').value||'غير محدد'],['الدولة',byId('country').value],['المستخدمون',req.users],['الفروع',req.branches],['المستودعات',req.warehouses],['الفواتير',req.invoices],['الموظفون',req.employees],['التصنيع',req.manufacturing?'نعم':'لا'],['الباقة',selected.plan.name],['السعر',currency(price.shown)+' ر.س']];byId('customerSummary').innerHTML=items.map(([label,value])=>`<div><span>${label}</span><b>${value}</b></div>`).join('');renderRoi(price.shown);}
function renderHistory(){byId('quoteHistory').innerHTML=quoteHistory().map((quote,index)=>`<div><b>${quote.customer||'عميل بدون اسم'}</b><br>${quote.date} · ${quote.plan}<br><button class="btn" onclick="loadQuote(${index})">تعديل</button><button class="btn" onclick="deleteQuote(${index})">حذف</button></div>`).join('')||'لا توجد عروض محفوظة';}
function render(){renderPlans();renderDashboard();renderAssistant();const message=whatsAppText();byId('whatsAppMessage').value=message;byId('whatsAppLink').href='https://wa.me/?text='+encodeURIComponent(message);byId('vatDescription').textContent=vatEnabled()?'يعرض الأساسي والضريبة والإجمالي':'يعرض السعر الأساسي فقط';saveDraft();}

/* Events and utilities */
function copyText(value){navigator.clipboard?.writeText(value);alert('تم النسخ');}
function saveQuote(){const {selected}=recommendation(),price=displayPrice(selected.preTax),history=quoteHistory();history.unshift({customer:byId('customerName').value,date:new Date().toLocaleDateString('ar-SA'),plan:selected.plan.name,total:price.shown,form:JSON.parse(localStorage.getItem('daftraSalesAssistant')).data});localStorage.setItem('daftraQuoteHistory',JSON.stringify(history.slice(0,50)));renderHistory();}
window.loadQuote=index=>{const quote=quoteHistory()[index];Object.entries(quote.form).forEach(([id,value])=>{const element=byId(id);if(element)element.type==='checkbox'?element.checked=value:element.value=value;});render();};window.deleteQuote=index=>{const history=quoteHistory();history.splice(index,1);localStorage.setItem('daftraQuoteHistory',JSON.stringify(history));renderHistory();};
document.querySelectorAll('input,select,textarea').forEach(element=>element.addEventListener('input',render));document.querySelectorAll('.period').forEach(button=>button.addEventListener('click',()=>{billingPeriod=button.dataset.period;render();}));document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',()=>copyText(byId(button.dataset.copy).value||byId(button.dataset.copy).innerText)));byId('copyPricing').addEventListener('click',()=>copyText(whatsAppText()));byId('themeButton').addEventListener('click',()=>{document.body.classList.toggle('dark');saveDraft();});byId('newCustomerButton').addEventListener('click',()=>{if(confirm('مسح بيانات العميل الحالي؟')){document.querySelectorAll('input,textarea').forEach(element=>element.type==='checkbox'?element.checked=false:element.value='');render();}});byId('proposalButton').addEventListener('click',()=>{if(!byId('customerName').value.trim())return alert('يرجى إدخال اسم العميل أولاً');byId('proposalSheet').innerHTML=buildProposal();byId('proposalModal').classList.add('show');});byId('saveQuoteButton').addEventListener('click',saveQuote);byId('competitor').addEventListener('change',event=>{const tips={Excel:'دقة أعلى وتقارير لحظية بدون عمل يدوي.',Odoo:'دعم عربي وتجربة محلية أبسط.',SAP:'إطلاق أسرع وتكلفة ملكية أقل.',Oracle:'مرونة أسرع وتكلفة أبسط.',Qoyod:'تشغيل أوسع للمبيعات والمخزون وHR.',Wafeq:'يتجاوز المحاسبة إلى التشغيل الكامل.'};byId('competitorTip').textContent=tips[event.target.value]||'اربط الاحتياج بأثر تشغيلي ملموس.';});
restoreDraft();render();renderHistory();
